FROM python:3.10

WORKDIR /app

# Copy all project files including app/ and requirements.txt
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the script
CMD ["python", "app/main.py"]
